spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://127.0.0.1:3306/mscs?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF8

  freemarker:
    cache: false

  devtools:
    restart:
      enabled: true

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.com.example.demo.entity


# »’÷æ≈‰÷√
logging:
  level:
    mapper: DEBUG
    org.springframework: INFO
    org.spring.springboot.dao: INFO
  file: logs/spring-boot-logging.log

server:
  tomcat:
    uri-encoding: UTF-8


